name = "DispatchDoctor"
uuid = "8d63f2c5-f18a-4cf2-ba9d-b3f60fc568c8"
authors = ["MilesCranmer <miles.cranmer@gmail.com> and contributors"]
version = "0.4.27"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"

[weakdeps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
EnzymeCore = "f151be2c-9106-41f4-ab19-57ee4f262869"

[extensions]
DispatchDoctorChainRulesCoreExt = "ChainRulesCore"
DispatchDoctorEnzymeCoreExt = "EnzymeCore"

[compat]
ChainRulesCore = "1"
EnzymeCore = "0.6, 0.7, 0.8"
MacroTools = "0.5"
Preferences = "1"
julia = "1.10"

[extras]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
EnzymeCore = "f151be2c-9106-41f4-ab19-57ee4f262869"
